import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {Enrollment} from '../dist/enrollment.js';
import {tokenTransaction} from '../dist/token-store.js';
import {authenticate,digest} from '../dist/security.js';
import {createApp} from '../dist/server.js';
import {configuration} from '../dist/config.js';
import {mergeMarketplace} from '../windows-setup/setup-client.mjs';
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'enrollment-')),file=path.join(root,'tokens.json');await writeFile(file,JSON.stringify([{name:'primary',sha256:digest('admin')} ]));let now=Date.now();const service=new Enrollment(file,()=>now);await service.list();t.after(()=>rm(root,{recursive:true,force:true}));return {root,file,service,advance:n=>now+=n};}
test('approval requires code, secret, acknowledgement; receive and ack retry safely',async t=>{const {file,service:s}=await fixture(t);const r=await s.create('laptop');await assert.rejects(()=>s.receive(r.id,r.secret));await assert.rejects(()=>s.status(r.id,'wrong'));await assert.rejects(()=>s.approve(r.id,'00000000'));assert.equal((await s.list()).requests[0].code,undefined);await s.approve(r.id,r.code);await assert.rejects(()=>s.approve(r.id,r.code));const {token}=await s.receive(r.id,r.secret);assert.equal(await authenticate(file,'Bearer '+token),undefined);assert.equal((await s.receive(r.id,r.secret)).token,token);await s.acknowledge(r.id,r.secret);await s.acknowledge(r.id,r.secret);assert.equal(await authenticate(file,'Bearer '+token),'laptop');await assert.rejects(()=>s.receive(r.id,r.secret));await s.revoke('laptop');assert.equal(await authenticate(file,'Bearer '+token),undefined);assert.equal(await authenticate(file,'Bearer admin'),'primary');});
test('rejection, expiry and restart revoke incomplete credentials while keeping completed ones',async t=>{const {file,service:s,advance}=await fixture(t);const rejected=await s.create('rejected');await s.reject(rejected.id);await assert.rejects(()=>s.approve(rejected.id,rejected.code));const r=await s.create('expires');await s.approve(r.id,r.code);advance(600001);await assert.rejects(()=>s.receive(r.id,r.secret));assert.equal(JSON.parse(await readFile(file,'utf8')).some(e=>e.name==='expires'),false);const pending=await s.create('unfinished');await s.approve(pending.id,pending.code);const done=await s.create('done');await s.approve(done.id,done.code);await s.acknowledge(done.id,done.secret);const reboot=new Enrollment(file);const list=await reboot.list();assert.deepEqual(list.devices.map(e=>e.name),['primary','done']);await assert.rejects(()=>reboot.status(pending.id,pending.secret));});
test('concurrent credential mutations and duplicate approval cannot lose records',async t=>{const {file,service:s}=await fixture(t);await Promise.all(Array.from({length:12},(_,i)=>tokenTransaction(file,e=>e.push({name:'device'+i,sha256:digest('key'+i)}))));assert.equal(JSON.parse(await readFile(file,'utf8')).length,13);const r=await s.create('race');const results=await Promise.allSettled([s.approve(r.id,r.code),s.approve(r.id,r.code)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);});
test('public setup APIs require request secret, admin APIs require session and CSRF',async t=>{const {root}=await fixture(t),config=configuration({DATA_DIR:root,SITE_IP:'127.0.0.1'});const server=createApp(config,{list:async()=>[]}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>{server.closeAllConnections();server.close(r);}));const base='http://127.0.0.1:'+server.address().port;const post=(url,body={},headers={})=>fetch(base+url,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});assert.equal((await fetch(base+'/setup')).status,200);assert.equal((await fetch(base+'/api/devices')).status,401);assert.equal((await post('/setup/api/requests',{name:'x'},{Origin:'https://evil.test'})).status,403);const r=await (await post('/setup/api/requests',{name:'laptop'})).json();assert.equal((await post('/setup/api/requests/'+r.id+'/receive')).status,400);const login=await post('/api/login',{token:'admin'},{Origin:config.origin});const {csrf}=await login.json();const headers={Cookie:login.headers.get('set-cookie').split(';')[0],Origin:config.origin};const url='/api/devices/requests/'+r.id+'/approve';assert.equal((await post(url,{code:r.code},headers)).status,403);assert.equal((await post(url,{code:r.code},{...headers,'X-CSRF-Token':csrf})).status,200);for(let i=0;i<4;i++)await post('/setup/api/requests',{name:'request'+i});assert.equal((await post('/setup/api/requests',{name:'overflow'})).status,429);});
test('marketplace merge preserves other plugins and metadata, rejects malformed names',()=>{const other={name:'other',source:{source:'local',path:'./plugins/other'}};const data=mergeMarketplace({name:'personal',interface:{displayName:'Mine'},plugins:[other]});assert.equal(data.plugins[0],other);assert.equal(data.interface.displayName,'Mine');assert.equal(data.plugins[1].source.path,'./plugins/local-sites');assert.throws(()=>mergeMarketplace({name:'../bad',plugins:[]}));});
