import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, appendFile, readdir, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import { Metrics, DockerMetrics, HostMetrics, aggregate, cpuPercent, containerValues, rate, emptyValues } from '../dist/metrics.js';
import { configuration } from '../dist/config.js';
import { Manager } from '../dist/manager.js';
import { createApp } from '../dist/server.js';
import { digest } from '../dist/security.js';

const GiB=1024**3;
function info(id='one'){return {Id:id,Config:{Labels:{'local-sites.app':'demo'}},State:{Status:'running'},HostConfig:{NanoCpus:1e9,Memory:512*1024**2}};}
function stats(rx=1000,tx=500){return {cpu_stats:{online_cpus:4,cpu_usage:{total_usage:200},system_cpu_usage:1800},precpu_stats:{cpu_usage:{total_usage:100},system_cpu_usage:1000},memory_stats:{usage:300,limit:512,stats:{inactive_file:100}},networks:{eth0:{rx_bytes:rx,tx_bytes:tx}}};}
function host(at,cpu=15){return {...emptyValues(),status:'running',collectedAt:at,storageAt:at,cpu,memory:25,memoryUsed:GiB,memoryLimit:4*GiB,cpuLimit:4,rx:1200,tx:500,storage:20*GiB,uptime:3600,interface:'eno1',disks:[{name:'OS',total:100*GiB,used:20*GiB,available:80*GiB,percent:20}]};}
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'metrics-'));t.after(()=>rm(root,{recursive:true,force:true}));const manager=new Manager(configuration({DATA_DIR:root,SITE_IP:'127.0.0.1'}),{run:async()=>JSON.stringify([info()])});await manager.init();manager.state.apps.demo={id:'demo',port:18000,url:'https://127.0.0.1:18000',desired:'running'};let now=Date.UTC(2026,8,16,0),mode='running',volumeFail=false,cpu=15,calls=0;
 const engine={get:async endpoint=>{calls++;if(endpoint.includes('/system/df')){if(volumeFail)throw Error('failure');return {Volumes:[{Name:'local-sites-data-demo',UsageData:{Size:1234}},{Name:'unrelated',UsageData:{Size:9999}}]};}if(endpoint.endsWith('/json')){if(mode==='fail')throw Error('timeout');const value=info(mode==='replaced'?'two':'one');if(mode==='stopped')value.State.Status='exited';if(mode==='mismatch')value.Config.Labels['local-sites.app']='other';return value;}return stats(now,now/2);}};
 const metrics=new Metrics(manager,engine,{collect:async at=>host(at,cpu)},()=>now);await metrics.init();
 return {root,manager,metrics,engine,clock:()=>now,advance:(n=30000)=>now+=n,mode:v=>mode=v,volumeFail:()=>volumeFail=true,cpu:v=>cpu=v,calls:()=>calls};}

test('CPU normalization, cache exclusion, limits and counter resets',()=>{assert.equal(cpuPercent([150,0,50,700,100,0,0,0],[100,0,0,300,100,0,0,0]),20);assert.equal(cpuPercent([1,0,0,1,0,0,0,0]),null);assert.equal(rate(2000,1000,1000),1000);assert.equal(rate(10,1000,1000),null);let result=containerValues(info(),stats(),undefined,1000);assert.equal(result.values.cpu,50);assert.equal(result.values.memoryUsed,200);assert.equal(result.values.memory,200/512*100);assert.equal(result.values.rx,null);result=containerValues(info(),stats(2000,2500),result.previous,2000);assert.equal(result.values.rx,1000);assert.equal(result.values.tx,2000);assert.equal(containerValues(info('new'),stats(),result.previous,3000).values.rx,null);assert.equal(containerValues(info(),stats(1,1),result.previous,3000).values.rx,null);assert.equal(containerValues(info(),stats(),result.previous,100000).values.rx,null);const unlimited=info();unlimited.HostConfig={};assert.equal(containerValues(unlimited,stats()).values.cpu,12.5);const quota=info();quota.HostConfig={CpuQuota:50000,CpuPeriod:100000};assert.equal(containerValues(quota,stats()).values.cpuLimit,.5);});

test('host reads host proc and deduplicates filesystem, never container CPU',async t=>{const root=await mkdtemp(path.join(os.tmpdir(),'host-metrics-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(path.join(root,'net'));await writeFile(path.join(root,'stat'),'cpu 100 0 0 300 100 0 0 0 0 0\ncpu0 0\ncpu1 0\n');await writeFile(path.join(root,'meminfo'),'MemTotal: 1024 kB\nMemAvailable: 256 kB\n');await writeFile(path.join(root,'uptime'),'600 900');await writeFile(path.join(root,'net/route'),'Iface Destination\neno1 00000000\n');await writeFile(path.join(root,'net/dev'),'eno1: 1000 0 0 0 0 0 0 0 2000 0 0 0 0 0 0 0\n');const source=new HostMetrics(root,root,root,'192.0.2.1','eno1');assert.equal((await source.collect(1000)).cpu,null);await writeFile(path.join(root,'stat'),'cpu 150 0 50 700 100 0 0 0 0 0\ncpu0 0\ncpu1 0\n');await writeFile(path.join(root,'net/dev'),'eno1: 2000 0 0 0 0 0 0 0 4000 0 0 0 0 0 0 0\n');const value=await source.collect(2000);assert.equal(value.cpu,20);assert.equal(value.memory,75);assert.equal(value.cpuLimit,2);assert.equal(value.rx,1000);assert.equal(value.disks.length,1);assert.equal(value.disks[0].name,'OS・アプリ保存領域');});

test('sampling, ownership, volume failure, stop/redeploy and purge visibility',async t=>{const f=await fixture(t);await f.metrics.collectVolumes();await f.metrics.sample();assert.equal(f.metrics.current().apps.demo.storage,1234);f.advance();await f.metrics.sample();assert.equal(f.metrics.current().apps.demo.rx,1000);f.mode('replaced');f.advance();await f.metrics.sample();assert.equal(f.metrics.current().apps.demo.rx,null);f.mode('mismatch');f.advance();await f.metrics.sample();assert.equal(f.metrics.current().apps.demo.cpu,null);assert.ok(f.metrics.current().apps.demo.error);f.mode('stopped');f.advance();await f.metrics.sample();assert.equal(f.metrics.current().apps.demo.status,'exited');assert.equal(f.metrics.current().apps.demo.cpu,null);f.manager.state.apps.demo.deletedAt='today';f.advance();await f.metrics.sample();assert.equal(f.metrics.current().apps.demo.status,'deleted');assert.equal(f.metrics.current().apps.demo.storage,1234);f.volumeFail();await f.metrics.collectVolumes();assert.equal(f.metrics.current().volumeError,true);assert.equal(f.metrics.current().apps.demo.storage,1234);delete f.manager.state.apps.demo;assert.equal(f.metrics.current().apps.demo,undefined);assert.throws(()=>f.metrics.getHistory('1h','demo'));});

test('overlapping reads share a collector and polling does not trigger Docker',async t=>{const f=await fixture(t);const first=f.metrics.sample(),second=f.metrics.sample();assert.equal(first,second);await first;const before=f.calls();for(let i=0;i<10;i++){f.metrics.current();f.metrics.getHistory('7d');}assert.equal(f.calls(),before);});

test('history restores after interrupted append, expires old files, gaps stay null',async t=>{const f=await fixture(t);await f.metrics.sample();const dir=path.join(f.root,'metrics'),today=(await readdir(dir))[0];await appendFile(path.join(dir,today),'partial invalid JSON');f.advance();await f.metrics.sample();await writeFile(path.join(dir,'2026-09-01.jsonl'),'old');const reload=new Metrics(f.manager,f.engine,{collect:async at=>host(at)},f.clock);await reload.init();const p=reload.getHistory('1h').points;assert.equal(p.filter(p=>p.average.cpu!==null).length,2);assert.ok(p.some(p=>p.average.cpu===null));assert.ok(!(await readdir(dir)).includes('2026-09-01.jsonl'));assert.equal(reload.current().host.cpu,15);assert.throws(()=>reload.getHistory('year'));f.advance(8*86400000);await reload.sample();assert.equal(reload.getHistory('7d').points.filter(p=>p.average.cpu!==null).length,1);});

test('aggregation returns average and peak at bounded 7-day resolution',()=>{const now=Date.UTC(2026,8,16),samples=[{timestamp:now-60000,host:host(now-60000,20),apps:{}},{timestamp:now-30000,host:host(now-30000,80),apps:{}}];const result=aggregate(samples,'7d',now);assert.equal(result.step,900000);assert.ok(result.points.length<=673);const p=result.points.find(p=>p.average.cpu!==null);assert.equal(p.average.cpu,50);assert.equal(p.peak.cpu,80);assert.equal(result.points.at(-1).average.cpu,null);});

test('warnings require continuous 3 minutes, survive level changes and clear on gaps',async t=>{const f=await fixture(t);f.cpu(90);for(let i=0;i<6;i++){await f.metrics.sample();assert.equal(f.metrics.current().warnings.length,0);f.advance();}f.cpu(96);await f.metrics.sample();assert.equal(f.metrics.current().warnings[0].level,'warning');for(let i=0;i<6;i++){f.advance();await f.metrics.sample();}assert.equal(f.metrics.current().warnings[0].level,'critical');f.advance(120000);await f.metrics.sample();assert.equal(f.metrics.current().warnings.length,0);f.cpu(20);f.advance();await f.metrics.sample();assert.equal(f.metrics.current().warnings.length,0);f.advance(100000);assert.equal(f.metrics.current().stale,true);});

test('metrics API shares portal authentication and validates requests',async t=>{const f=await fixture(t);await f.metrics.sample();await writeFile(f.manager.config.tokenFile,JSON.stringify([{name:'test',sha256:digest('test-secret')}]));const server=createApp(f.manager.config,f.manager,f.metrics).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});const base='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(base+'/api/metrics/current')).status,401);assert.equal((await fetch(base+'/api/metrics/history?range=1h')).status,401);const login=await fetch(base+'/api/login',{method:'POST',headers:{Origin:f.manager.config.origin,'Content-Type':'application/json'},body:JSON.stringify({token:'test-secret'})});const headers={Cookie:login.headers.get('set-cookie').split(';')[0]};await login.json();assert.equal((await fetch(base+'/api/metrics/current',{headers})).status,200);assert.equal((await fetch(base+'/api/metrics/history?range=7d&appId=demo',{headers})).status,200);assert.equal((await fetch(base+'/api/metrics/history?range=bad',{headers})).status,400);assert.equal((await fetch(base+'/api/metrics/history?range=1h&appId=missing',{headers})).status,400);assert.equal((await fetch(base+'/api/metrics/history?range=1h&range=7d',{headers})).status,400);await writeFile(f.manager.config.tokenFile,'[]');assert.equal((await fetch(base+'/api/metrics/current',{headers})).status,401);});

test('Docker metrics transport negotiates version and enforces total timeout',async t=>{const pipe=process.platform==='win32'?'\\\\.\\pipe\\metrics-'+process.pid+'-'+Date.now():path.join(os.tmpdir(),'metrics-'+process.pid+'.sock');const requests=[];const server=http.createServer((req,res)=>{requests.push(req.url);if(req.url==='/version')res.end(JSON.stringify({ApiVersion:'1.54'}));else if(req.url.endsWith('/ok'))res.end('{"ok":true}');});server.listen(pipe);await new Promise(r=>server.once('listening',r));t.after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));});const engine=new DockerMetrics(pipe);assert.deepEqual(await engine.get('/ok'),{ok:true});await assert.rejects(()=>engine.get('/hang',50),/timeout/);assert.deepEqual(requests,['/version','/v1.54/ok','/v1.54/hang']);});
