import { portalStyle } from './portal-style.js';
import { portalScript } from './portal-script.js';
export { portalScript };
export const portalHtml = `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>Local Sites — リソース監視</title><style>${portalStyle}</style></head><body><a class="skip-link" href="#main-content">本文へ移動</a>
<header><div class="brand"><span class="mark" aria-hidden="true">▥</span><div><strong>Local Sites</strong><small>SERVER & APPLICATIONS</small></div></div><div class="header-actions"><span id="connection" class="connection" hidden><span class="dot"></span><span id="connectionText">接続中</span></span><a class="link" href="/devices">端末管理</a><button id="logout" hidden>ログアウト</button></div></header>
<div id="viewNav" class="view-nav" hidden><div class="view-tabs" role="tablist" aria-label="管理画面の表示"><button id="tab-server" type="button" role="tab" aria-selected="true" aria-controls="panel-server" tabindex="0"><span aria-hidden="true">▥</span> サーバー</button><button id="tab-apps" type="button" role="tab" aria-selected="false" aria-controls="panel-apps" tabindex="-1"><span aria-hidden="true">▦</span> アプリ <span id="tabAppCount" class="tab-count" aria-hidden="true">0</span></button></div></div><main id="main-content" tabindex="-1"><div id="message" class="notice" role="status" hidden></div><section id="login" class="login"><p class="eyebrow">LOCAL SITES</p><h2>管理ポータルへログイン</h2><p class="muted">サーバーとアプリの状態を、ひとつの場所で。</p><form id="loginForm"><label for="token">端末用の認証キー</label><input id="token" type="password" autocomplete="current-password" required><button class="primary">ログイン</button></form><p class="muted">接続は8時間有効です。設定済み端末の primary.token のキーを使用できます。キーはURLやブラウザーの保存領域に記録しません。</p></section>
<section id="dashboard" hidden><div class="intro"><div><p id="viewEyebrow" class="eyebrow">RESOURCE MONITOR</p><h1 id="viewTitle">サーバーの今を、ひと目で。</h1><p id="viewDescription" class="muted">リソースの余裕と、アプリごとの動きを確認。</p></div><div class="intro-right"><button id="refresh">↻ 更新</button><div id="updatedAt" class="muted">計測を準備中</div></div></div><section id="compactSummary" class="compact-summary" aria-label="サーバー全体の現在値" hidden></section><div id="alerts" class="notice" hidden></div><div id="alertAnnouncement" class="sr-only" role="status" aria-live="polite" aria-atomic="true"></div><section id="panel-server" role="tabpanel" aria-labelledby="tab-server" tabindex="-1"><div id="summary" class="summary-grid"></div>
<div class="section-head"><h2>リソースの推移 <span class="muted">サーバー全体</span></h2><div id="range" class="segment" role="group" aria-label="表示期間"><button data-range="1h" aria-pressed="true">1時間</button><button data-range="24h" aria-pressed="false">24時間</button><button data-range="7d" aria-pressed="false">7日</button></div></div><div id="hostCharts" class="chart-grid"></div><p class="muted history-note">30秒ごとに計測・過去7日を保存。グラフのスライダーは矢印キーで操作できます。欠測期間は線をつなぎません。</p>
</section><section id="panel-apps" role="tabpanel" aria-labelledby="tab-apps" tabindex="-1" hidden><div class="section-head"><h2>アプリ一覧 <span id="count" class="muted"></span></h2><div class="toolbar"><input id="search" type="search" placeholder="アプリ名で検索" aria-label="アプリ名で検索"><select id="sort" aria-label="アプリの並べ替え"><option value="name">名前順</option><option value="cpu">CPUが高い順</option><option value="memoryUsed">メモリが多い順</option><option value="storage">保存容量が多い順</option></select></div></div><div id="appList" class="app-grid"></div></section><div class="footer"><span id="hostInfo">サーバー情報を取得中</span><span>LOCAL SITES · PRIVATE INFRASTRUCTURE</span></div></section></main>
<dialog id="logs" aria-labelledby="logsTitle"><div class="dialog-head"><h2 id="logsTitle">アプリのログ</h2><button id="closeLogs">閉じる</button></div><pre id="logText"></pre></dialog>
<dialog id="detail" aria-labelledby="detailTitle"><div class="dialog-head"><div><p class="eyebrow">APPLICATION RESOURCES</p><h2 id="detailTitle"></h2></div><button id="closeDetail">閉じる</button></div><p id="detailNote" class="muted"></p><div id="detailStats" class="detail-stats"></div><div class="section-head"><h3>リソースの推移</h3><div id="detailRange" class="segment" role="group" aria-label="アプリの表示期間"><button data-range="1h" aria-pressed="true">1時間</button><button data-range="24h" aria-pressed="false">24時間</button><button data-range="7d" aria-pressed="false">7日</button></div></div><div id="detailCharts" class="chart-grid"></div><p class="muted">CPUは割り当て上限に対する使用率です。メモリは再利用可能なファイルキャッシュを除いた使用量。保存容量は /data のボリューム使用量で、イメージやログを含みません。</p></dialog><script src="/portal.js" defer></script></body></html>`;
