export const portalScript = String.raw`
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg';
let csrf='', apps=[], metrics=null, hostHistory=null, detailHistory=null, busy=false, refreshing=false, range='1h', detailRange='1h', detailId='', generation=0;
const cards=new Map(), charts=new Map();
let previewId='', previewBusy=false;

let currentView='server', viewInitialized=false, alertSignature='';
const viewScroll={server:0,apps:0};
const requestedView=()=>location.hash==='#apps'?'apps':'server';
if('scrollRestoration' in history)history.scrollRestoration='manual';
function selectView(view,{push=false,focus=false}={}){
 if($('dashboard').hidden)return;
 view=view==='apps'?'apps':'server';
 const changed=!viewInitialized||view!==currentView;
 if(viewInitialized)viewScroll[currentView]=scrollY;
 if(changed){$('detail').close();$('logs').close();$('previewDialog').close();detailId='';}
 currentView=view;viewInitialized=true;
 if(push&&location.hash!=='#'+view)history.pushState(null,'','#'+view);
 else if(location.hash!=='#server'&&location.hash!=='#apps')history.replaceState(null,'','#'+view);
 for(const name of ['server','apps']){const active=name===view;$('tab-'+name).setAttribute('aria-selected',String(active));$('tab-'+name).tabIndex=active?0:-1;$('panel-'+name).hidden=!active;}
 $('compactSummary').hidden=view!=='apps';
 $('viewTitle').textContent=view==='server'?'サーバーの今を、ひと目で。':'アプリを、すぐ手元に。';
 $('viewEyebrow').textContent=view==='server'?'RESOURCE MONITOR':'APPLICATIONS';
 $('viewDescription').textContent=view==='server'?'リソースの余裕と、負荷の推移を確認。':'アプリの状態を確認し、必要な操作へすぐにアクセス。';
 document.title=(view==='server'?'サーバー':'アプリ')+' — Local Sites';
 renderSummary();
 if(view==='apps')renderApps();else renderCharts($('hostCharts'),'host',hostHistory);
 if(focus)$('tab-'+view).focus({preventScroll:true});
 if(changed)window.scrollTo({top:viewScroll[view],behavior:'instant'});
}
function renderCompact(){const h=metrics?.host||{},disks=h.disks||[],used=disks.reduce((n,d)=>n+d.used,0),available=disks.reduce((n,d)=>n+d.available,0);const fragment=document.createDocumentFragment();fragment.append(element('h2','サーバー全体'));
 for(const [label,value,note]of [['CPU',pct(h.cpu),''],['メモリ',pct(h.memory),bytes(h.memoryUsed)+' / '+bytes(h.memoryLimit)],['ディスク',disks.length?pct(used/(used+available)*100):'—','空き '+(disks.length?bytes(available):'—')]]){const item=element('div','','compact-item');item.append(element('span',label),element('strong',value));if(note)item.append(element('small',note));fragment.append(item);}
 $('compactSummary').replaceChildren(fragment);
}
function renderActiveCharts(){if(!$('dashboard').hidden&&currentView==='server')renderCharts($('hostCharts'),'host',hostHistory);if($('detail').open)renderDetail();}

const num=v=>typeof v==='number'&&Number.isFinite(v), pct=v=>num(v)?v.toFixed(1)+'%':'—';
function bytes(value){if(!num(value))return '—';const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(value>=1024&&i<4){value/=1024;i++;}return value.toFixed(i===0?0:value>=100?0:1)+' '+units[i];}
const speed=v=>num(v)?bytes(v)+'/s':'—';
function time(v,full=false){return v?new Date(v).toLocaleString('ja-JP',full?{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}:{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'未取得';}
function element(tag,text='',cls=''){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;}
function svg(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;}
function message(text){$('message').textContent=text;$('message').hidden=!text;}
function signedIn(value){$('login').hidden=value;$('dashboard').hidden=!value;$('logout').hidden=!value;$('connection').hidden=!value;$('viewNav').hidden=!value;if(value){for(const c of cards.values())if(c.image.hidden)c.image.removeAttribute('src');selectView(requestedView());}if(!value){generation++;$('detail').close();$('logs').close();$('previewDialog').close();detailId='';}}
async function api(path,data){const response=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(15000)});if(response.status===401){signedIn(false);throw Error('認証キーを確認してログインしてください。');}if(!response.ok){let result;try{result=await response.json()}catch{}throw Error(result?.error||(response.status===429?'試行回数が多いため、1分後に再試行してください。':'情報を取得できません ('+response.status+')'));}return response.json();}
function meter(value,blue=false){const n=element('div','','meter'+(blue?' blue':'')+(value>=95?' critical':value>=85?' warn':'')),bar=element('span');bar.style.width=(num(value)?Math.min(100,Math.max(0,value)):0)+'%';n.append(bar);return n;}
function metricCard(title,value,sub,note,percent,symbol,blue=false){const n=element('article','','metric-card'),head=element('div','','metric-head');head.append(element('span',title),element('span',symbol,'metric-symbol'));n.append(head,element('div',value,'metric-value'));if(percent!==undefined)n.append(meter(percent,blue));else n.append(element('div','送受信速度','metric-sub'));n.append(element('div',sub,'metric-sub'),element('div',note,'metric-sub'));return n;}
function renderSummary(){renderCompact();const h=metrics?.host||{},disks=h.disks||[],total=disks.reduce((s,d)=>s+d.total,0),used=disks.reduce((s,d)=>s+d.used,0),available=disks.reduce((s,d)=>s+d.available,0);$('summary').replaceChildren(metricCard('CPU 使用率',pct(h.cpu),'全 '+(h.cpuLimit||'—')+' コアに対する使用率',num(h.cpu)?'余裕 '+pct(Math.max(0,100-h.cpu)):'次回の計測を待っています',h.cpu,'CPU'),metricCard('メモリ',bytes(h.memoryUsed),'/ '+bytes(h.memoryLimit),num(h.memoryUsed)&&num(h.memoryLimit)?'空き '+bytes(h.memoryLimit-h.memoryUsed):'取得待ち',h.memory,'RAM',true),metricCard('ディスク',total?pct(used/(used+available)*100):'—',total?bytes(used)+' / '+bytes(total):'取得待ち',total?'空き '+bytes(available):'OS・アプリ保存領域',total?used/(used+available)*100:null,'DISK'),metricCard('ネットワーク',speed(h.rx),'↓ 受信　↑ 送信 '+speed(h.tx),h.interface||'LANインターフェース',undefined,'NET'));
 $('updatedAt').textContent='最終取得 '+time(h.collectedAt)+' · 30秒更新';const stale=!h.collectedAt||Date.now()-h.collectedAt>90000;$('connection').classList.toggle('warn',stale);$('connectionText').textContent=stale?'更新遅延':'モニタリング中';const alerts=(metrics?.warnings||[]).map(w=>w.message);if(stale)alerts.unshift('更新遅延：サーバーの最新リソース情報を取得できていません。');if(h.error)alerts.push(h.error);if(metrics?.volumeError)alerts.push('保存容量の更新に失敗しました。最後に取得できた値を表示しています。');if(metrics?.storageError)alerts.push('履歴の保存に失敗しています。');const unavailable=Object.values(metrics?.apps||{}).filter(a=>a.error).length;if(unavailable)alerts.push(unavailable+'件のアプリ統計を取得できていません。');if($('alerts').textContent!==alerts.join('\n'))$('alerts').textContent=alerts.join('\n');const signature=JSON.stringify({warnings:(metrics?.warnings||[]).map(w=>[w.entity,w.metric,w.level]),stale,error:h.error,volume:metrics?.volumeError,storage:metrics?.storageError,unavailable:Object.entries(metrics?.apps||{}).filter(([,a])=>a.error).map(([id])=>id).sort()});if(metrics&&signature!==alertSignature){$('alertAnnouncement').textContent=alerts.length?alerts.join('。'):alertSignature?'注意状態は解消しました。':'';alertSignature=signature;}$('alerts').hidden=!alerts.length;$('alerts').classList.toggle('critical',(metrics?.warnings||[]).some(w=>w.level==='critical'));
 $('hostInfo').textContent='稼働時間 '+(num(h.uptime)?Math.floor(h.uptime/86400)+'日 '+Math.floor(h.uptime%86400/3600)+'時間':'—')+' · '+disks.map(d=>d.name+' '+pct(d.percent)+' / 空き '+bytes(d.available)).join(' · ');
}
function drawSeries(target,points,keys,format,maxFixed){const width=Math.max(280,target.parentElement.clientWidth||540),height=148,left=48,right=10,top=10,bottom=25,plotW=width-left-right,plotH=height-top-bottom;target.replaceChildren();target.setAttribute('viewBox','0 0 '+width+' '+height);target.setAttribute('preserveAspectRatio','none');const values=points.flatMap(p=>keys.flatMap(k=>[p.average[k],p.peak[k]])).filter(num),max=maxFixed||Math.max(1,...values)*1.12;
 for(let i=0;i<3;i++){const y=top+i*plotH/2;target.append(svg('line',{x1:left,y1:y,x2:width-right,y2:y,stroke:'#293a50','stroke-dasharray':'3 5'}));const t=svg('text',{x:left-7,y:y+4,'text-anchor':'end'});t.textContent=format(max*(1-i/2));target.append(t);}
 const x=i=>left+i/Math.max(1,points.length-1)*plotW, y=v=>top+plotH-Math.min(max,Math.max(0,v))/max*plotH;
 keys.forEach((key,index)=>{for(const mode of ['peak','average']){let d='',pen=false;const present=points.filter(p=>num(p[mode][key])).length;points.forEach((p,i)=>{const value=p[mode][key];if(!num(value)){pen=false;return;}if(mode==='average'&&present===1)target.append(svg('circle',{cx:x(i),cy:y(value),r:3,fill:index?'#7eaaff':'#56dfc1'}));d+=(pen?' L':' M')+x(i).toFixed(2)+' '+y(value).toFixed(2);pen=true;});target.append(svg('path',{d,fill:'none',stroke:index?'#7eaaff':'#56dfc1','stroke-width':mode==='peak'?1:2,'stroke-opacity':mode==='peak'?.32:1,'stroke-dasharray':mode==='peak'?'3 3':'none','vector-effect':'non-scaling-stroke'}));}});
 if(points.length){for(const i of [0,Math.floor((points.length-1)/2),points.length-1]){const t=svg('text',{x:x(i),y:height-4,'text-anchor':i===0?'start':i===points.length-1?'end':'middle'});t.textContent=new Date(points[i].at).toLocaleString('ja-JP',points.length>200?{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}:{hour:'2-digit',minute:'2-digit'});target.append(t);}}
 return values.length>0;
}
function chart(container,id,title,keys,labels,format,history,fixed){let c=charts.get(id);if(!c){const card=element('article','','chart-card'),top=element('div','','chart-top'),stats=element('span','','chart-stats'),legend=element('div','','chart-legend'),area=element('div','','chart-area'),drawing=svg('svg',{'aria-hidden':'true'}),empty=element('div','この期間の計測データはまだありません','empty-chart'),readout=element('div','','chart-readout'),slider=element('input');slider.type='range';slider.min='0';slider.step='1';slider.setAttribute('aria-label',title+'の時刻を選択');top.append(element('h3',title),stats);labels.forEach((label,i)=>{const item=element('span');item.append(element('i','','legend-line'+(i?' blue':'')),document.createTextNode(label));legend.append(item);});area.append(drawing,empty);card.append(top,legend,area,slider,readout);container.append(card);c={card,stats,drawing,empty,readout,slider,points:[],follow:true};charts.set(id,c);slider.oninput=()=>{c.follow=Number(slider.value)===c.points.length-1;updateReadout(c,keys,labels,format);};}
 const selectedAt=c.points[Number(c.slider.value)]?.at;c.points=history?.points||[];const previous=selectedAt===undefined?Number(c.slider.value):Math.max(0,c.points.findIndex(p=>p.at>=selectedAt)),focused=document.activeElement===c.slider;c.slider.max=String(Math.max(0,c.points.length-1));c.slider.disabled=!c.points.length;if(!focused&&c.follow){const last=c.points.findLastIndex(p=>keys.some(k=>num(p.average[k])));c.slider.value=String(last<0?c.points.length-1:last);}else c.slider.value=String(Math.max(0,Math.min(previous,c.points.length-1)));c.empty.hidden=drawSeries(c.drawing,c.points,keys,format,fixed);const all=c.points.map(p=>p.average[keys[0]]).filter(num),peaks=c.points.map(p=>p.peak[keys[0]]).filter(num);c.stats.textContent=all.length?'平均 '+format(all.reduce((a,b)=>a+b,0)/all.length)+' · 最大 '+format(Math.max(...peaks)):'計測待ち';updateReadout(c,keys,labels,format);
}
function updateReadout(c,keys,labels,format){const p=c.points[Number(c.slider.value)];c.readout.textContent=p?time(p.at,true)+'　'+keys.map((k,i)=>labels[i]+' '+format(p.average[k])+'（最大 '+format(p.peak[k])+'）').join('　'):'データを収集中です';c.slider.setAttribute('aria-valuetext',c.readout.textContent);}
function renderCharts(container,prefix,history){if(container.closest('[hidden]')||(prefix==='detail'&&!$('detail').open))return;chart(container,prefix+'cpu','CPU 使用率',['cpu'],['CPU'],pct,history,100);chart(container,prefix+'memory','メモリ使用量',['memoryUsed'],['メモリ'],bytes,history);chart(container,prefix+'network','ネットワーク',['rx','tx'],['受信','送信'],speed,history);chart(container,prefix+'disk','保存容量',['storage'],[prefix==='host'?'ディスク使用量':'保存データ'],bytes,history);}
function spark(points){const n=svg('svg',{viewBox:'0 0 300 34',preserveAspectRatio:'none',class:'spark','aria-hidden':'true'});let d='',pen=false,last=0;points.forEach((p,i)=>{if(!num(p.value)||p.at-last>90000)pen=false;if(num(p.value)){d+=(pen?' L':' M')+(i/Math.max(1,points.length-1)*300).toFixed(1)+' '+(31-Math.min(100,p.value)/100*28).toFixed(1);pen=true;}last=p.at;});n.append(svg('line',{x1:0,x2:300,y1:32,y2:32,stroke:'#293b50'}),svg('path',{d,fill:'none',stroke:'#56dfc1','stroke-width':1.5,'vector-effect':'non-scaling-stroke'}));return n;}
function createCard(a){
 const card=element('article','','app-card'),preview=element('a','','app-preview'),image=element('img'),placeholder=element('span','プレビュー未取得','preview-placeholder'),caption=element('span','','preview-caption');
 preview.target='_blank';preview.rel='noopener noreferrer';preview.setAttribute('aria-label',a.id+'を開く');image.alt=a.id+'のトップページ';image.width=1280;image.height=720;image.loading='eager';image.decoding='async';image.hidden=true;preview.append(image,placeholder,caption);
 image.onerror=()=>{image.hidden=true;placeholder.hidden=false;placeholder.textContent='画像を表示できません';};image.onload=()=>{image.hidden=false;placeholder.hidden=true;};
 const body=element('div','','app-card-body'),head=element('div','','app-heading'),title=element('h3',a.id),badge=element('span','','badge'),url=element('p','','url'),resources=element('div'),actions=element('div','','actions'),more=element('details','','more'),secondary=element('div','','actions');head.append(title,badge);more.append(element('summary','その他の操作'),secondary);body.append(head,url,resources,actions,more);card.append(preview,body);
 const controls={};const button=(name,label,parent,fn,cls='')=>{const b=element('button',label,cls);b.onclick=()=>run(()=>fn(a.id));parent.append(b);controls[name]=b;};const link=element('a','開く','link primary');link.target='_blank';link.rel='noopener noreferrer';actions.append(link);
 button('detail','リソース詳細',actions,openDetail);button('toggle','停止',actions,async id=>{const running=apps.find(x=>x.id===id)?.status==='running';await api('/apps/'+id+(running?'/stop':'/start'),{});await refresh();});
 button('preview','プレビュー設定',secondary,openPreview);
 button('logs','ログ',secondary,async id=>{$('logText').textContent=(await api('/apps/'+id+'/logs')).logs;$('logs').showModal();});button('copy','URLをコピー',secondary,async id=>{await navigator.clipboard.writeText(apps.find(x=>x.id===id).url);message('URLをコピーしました。');});
 button('delete','削除',secondary,async id=>{if(!confirm(id+' を削除しますか？保存データとURLは保持され、再配置で復帰できます。'))return;await api('/apps/'+id+'/delete',{purge:false});await refresh();},'danger');button('purge','完全削除',secondary,async id=>{const v=prompt('保存データも完全に削除します。元に戻せません。確認のためアプリ名「'+id+'」を入力してください。');if(v===null)return;if(v!==id)throw Error('アプリ名が一致しません。削除していません。');await api('/apps/'+id+'/delete',{purge:true,confirmation:v});if(detailId===id)$('detail').close();await refresh();},'danger');
 return {card,badge,url,resources,controls,link,preview,image,placeholder,caption};
}
function previewLabel(p){return p?.state==='queued'?'撮影待ち':p?.state==='capturing'?'撮影中…':p?.state==='failed'?'撮影できませんでした':p?.mode==='manual'?'登録画像':p?.url?'LPプレビュー':'プレビュー未取得';}
function updatePreviewImage(image,placeholder,p){const url=p?.url||'';if(url){if(image.getAttribute('src')!==url){image.hidden=true;placeholder.hidden=false;placeholder.textContent='画像を読み込み中…';image.src=url;}}else{image.removeAttribute('src');image.hidden=true;placeholder.hidden=false;placeholder.textContent=previewLabel(p);}}
function renderPreviewDialog(){
 if(!$('previewDialog').open)return;const a=apps.find(x=>x.id===previewId);if(!a){$('previewDialog').close();return;}const p=a.preview||{};
 $('previewTitle').textContent=a.id+' のプレビュー';updatePreviewImage($('previewImage'),$('previewPlaceholder'),p);
 $('previewMeta').textContent=(p.mode==='manual'?'手動登録':'自動取得')+' · 更新 '+time(p.updatedAt,true);
 $('previewState').textContent=previewLabel(p)+(p.error?'。'+p.error:'');
 const pending=['queued','capturing'].includes(p.state),running=a.status==='running';
 $('capturePreview').hidden=p.mode==='manual';$('autoPreview').hidden=p.mode!=='manual';
 $('capturePreview').disabled=previewBusy||pending||!running;$('autoPreview').disabled=previewBusy||pending||!running;$('previewFile').disabled=previewBusy;
 $('previewRunningNote').hidden=running;
}
function openPreview(id){previewId=id;$('previewError').textContent='';$('previewFile').value='';$('previewDialog').showModal();renderPreviewDialog();}
async function previewAction(fn){if(previewBusy)return;previewBusy=true;const id=previewId,g=generation;$('previewError').textContent='';renderPreviewDialog();try{const result=await fn(id);if(g!==generation)return;const a=apps.find(x=>x.id===id);if(a)a.preview=result;renderApps();}catch(e){if(g===generation&&id===previewId)$('previewError').textContent=e.message;}finally{previewBusy=false;renderPreviewDialog();}}
function renderApps(){$('tabAppCount').textContent=String(apps.length);if($('dashboard').hidden||currentView!=='apps')return;const savedY=scrollY;const active=document.activeElement;const q=$('search').value.trim().toLowerCase(),sort=$('sort').value,filtered=apps.filter(a=>a.id.toLowerCase().includes(q)).sort((a,b)=>sort==='name'?a.id.localeCompare(b.id):(metrics?.apps?.[b.id]?.[sort]??-1)-(metrics?.apps?.[a.id]?.[sort]??-1)||a.id.localeCompare(b.id));$('count').textContent=apps.length+'件 · '+apps.filter(a=>a.status==='running').length+'件稼働中';for(const [id,c]of cards)if(!apps.some(a=>a.id===id)){c.card.remove();cards.delete(id);}for(const c of cards.values())c.card.hidden=true;
 filtered.forEach((a,i)=>{let c=cards.get(a.id);if(!c){c=createCard(a);cards.set(a.id,c);}c.card.hidden=false;const m=metrics?.apps?.[a.id]||{},running=a.status==='running',deleted=a.status==='deleted',stale=m.collectedAt&&Date.now()-m.collectedAt>90000;c.badge.textContent=deleted?'削除済み · データ保持':running?'稼働中':a.status==='exited'?'停止中':a.status;c.badge.className='badge'+(running?'':' off');c.url.textContent=a.url;c.link.href=a.url;c.link.hidden=!running;if(running){c.preview.href=a.url;c.preview.removeAttribute('aria-disabled');c.preview.tabIndex=0;}else{c.preview.removeAttribute('href');c.preview.setAttribute('aria-disabled','true');c.preview.tabIndex=-1;}updatePreviewImage(c.image,c.placeholder,a.preview);c.caption.textContent=previewLabel(a.preview);c.caption.hidden=!a.preview?.url||a.preview?.state==='ready';c.controls.toggle.textContent=running?'停止':'起動';for(const name of ['toggle','logs','copy','delete'])c.controls[name].hidden=deleted;for(const b of Object.values(c.controls))b.disabled=busy;
 const row=element('div','','app-resource-row');for(const [label,value,note,percent]of [['CPU',pct(m.cpu),'上限 '+(m.cpuLimit??'—')+' コア',m.cpu],['メモリ',bytes(m.memoryUsed),'/ '+bytes(m.memoryLimit),m.memory],['保存容量',bytes(m.storage),'取得 '+time(m.storageAt)+(m.storageAt&&Date.now()-m.storageAt>600000?' · 更新遅延':''),null]]){const col=element('div');col.title=note;col.append(element('span',label,'label'),element('strong',value,percent>=95?'resource-critical':percent>=85?'resource-warn':''));row.append(col);}const note=element('p',deleted?'同じIDで再配置すると保存データを再利用できます。':m.error?m.error:stale?'更新遅延：最後の計測値です。':'','app-note');note.hidden=!note.textContent;c.resources.replaceChildren(row,note);
 const at=$('appList').children[i];if(at!==c.card)$('appList').insertBefore(c.card,at||null);
 });let empty=$('emptyApps');if(!empty){empty=element('p','','muted');empty.id='emptyApps';$('appList').append(empty);}empty.textContent=apps.length?'該当するアプリがありません。':'まだアプリがありません。';empty.hidden=filtered.length>0;if(active?.isConnected&&document.activeElement!==active)active.focus({preventScroll:true});if(scrollY!==savedY)window.scrollTo({top:savedY,behavior:'instant'});
}
function renderDetail(){if(!detailId)return;const m=metrics?.apps?.[detailId]||{};$('detailTitle').textContent=detailId;$('detailNote').textContent='最終計測 '+time(m.collectedAt)+' · 保存容量の取得 '+time(m.storageAt)+(m.error?' · '+m.error:'');const values=[['CPU',pct(m.cpu),'上限 '+(m.cpuLimit??'—')+' コア'],['メモリ',bytes(m.memoryUsed),'/ '+bytes(m.memoryLimit)],['受信 / 送信',speed(m.rx),speed(m.tx)],['保存データ',bytes(m.storage),'5分ごとに計測']];$('detailStats').replaceChildren(...values.map(([label,value,note])=>{const n=element('div',label,'detail-stat');n.append(element('strong',value),element('small',note));return n;}));renderCharts($('detailCharts'),'detail',detailHistory);}
async function openDetail(id){detailId=id;detailHistory=null;$('detail').showModal();renderDetail();await fetchDetail();}
async function fetchDetail(){const id=detailId,r=detailRange,g=generation;if(!id)return;try{const data=await api('/metrics/history?range='+r+'&appId='+encodeURIComponent(id));if(id===detailId&&r===detailRange&&g===generation){detailHistory=data;renderDetail();}}catch(e){if(g===generation)$('detailNote').textContent=e.message;}}
async function fetchHistory(){const r=range,g=generation;try{const data=await api('/metrics/history?range='+r);if(r===range&&g===generation){hostHistory=data;if(currentView==='server')renderCharts($('hostCharts'),'host',hostHistory);}}catch(e){if(g===generation)message(e.message);}}
async function refresh(){if(refreshing)return;refreshing=true;const g=generation;try{const results=await Promise.allSettled([api('/apps'),api('/metrics/current')]);if(g!==generation)return;if(results[0].status==='fulfilled')apps=results[0].value;else message(results[0].reason.message);if(results[1].status==='fulfilled')metrics=results[1].value;else message(results[1].reason.message);renderSummary();renderApps();renderDetail();renderPreviewDialog();await Promise.all([fetchHistory(),$('detail').open?fetchDetail():Promise.resolve()]);}finally{refreshing=false;}}
async function run(fn){if(busy)return;busy=true;renderApps();message('');try{await fn();}catch(e){message(e.message);}finally{busy=false;renderApps();}}
$('loginForm').onsubmit=async e=>{e.preventDefault();const token=$('token').value;$('token').value='';await run(async()=>{csrf=(await api('/login',{token})).csrf;signedIn(true);await refresh();});};$('refresh').onclick=()=>run(refresh);$('search').oninput=renderApps;$('sort').onchange=renderApps;$('closeLogs').onclick=()=>$('logs').close();$('closeDetail').onclick=()=>$('detail').close();$('detail').onclose=()=>{detailId='';detailHistory=null;};$('logout').onclick=()=>run(async()=>{await api('/logout',{});csrf='';apps=[];metrics=null;signedIn(false);});
$('closePreview').onclick=()=>$('previewDialog').close();$('previewDialog').onclose=()=>{previewId='';$('previewFile').value='';};
$('previewImage').onload=()=>{$('previewImage').hidden=false;$('previewPlaceholder').hidden=true;};$('previewImage').onerror=()=>{$('previewImage').hidden=true;$('previewPlaceholder').hidden=false;$('previewPlaceholder').textContent='画像を表示できません';};
$('capturePreview').onclick=()=>previewAction(id=>api('/apps/'+id+'/preview/capture',{}));$('autoPreview').onclick=()=>previewAction(id=>api('/apps/'+id+'/preview/auto',{}));
$('previewFile').onchange=()=>{const file=$('previewFile').files[0];if(!file)return;void previewAction(async id=>{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('5MB以下のPNG・JPEG・WebPを選択してください。');const response=await fetch('/api/apps/'+id+'/preview/upload',{method:'POST',headers:{'Content-Type':file.type,'X-CSRF-Token':csrf},body:file,signal:AbortSignal.timeout(30000)});if(response.status===401){signedIn(false);throw Error('再度ログインしてください。');}const result=await response.json();if(!response.ok)throw Error(result.error||'画像を登録できませんでした。');$('previewFile').value='';return result;});};
for(const [id,isDetail]of [['range',false],['detailRange',true]])for(const b of $(id).querySelectorAll('button'))b.onclick=()=>{for(const sibling of $(id).querySelectorAll('button'))sibling.setAttribute('aria-pressed',String(sibling===b));if(isDetail){detailRange=b.dataset.range;void fetchDetail();}else{range=b.dataset.range;void fetchHistory();}};

for(const name of ['server','apps']){
 const tab=$('tab-'+name);tab.onclick=()=>selectView(name,{push:true});
 tab.onkeydown=e=>{let next;if(e.key==='ArrowRight'||e.key==='ArrowLeft')next=name==='server'?'apps':'server';else if(e.key==='Home')next='server';else if(e.key==='End')next='apps';else return;e.preventDefault();selectView(next,{push:true,focus:true});};
}
window.addEventListener('hashchange',()=>selectView(requestedView(),{focus:true}));
document.querySelector('.skip-link').onclick=e=>{e.preventDefault();const target=$('dashboard').hidden?$('main-content'):$('panel-'+currentView);target.focus({preventScroll:true});target.scrollIntoView({block:'start',behavior:'instant'});};
let resizeFrame;window.addEventListener('resize',()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(renderActiveCharts);});

(async()=>{try{csrf=(await api('/session')).csrf;signedIn(true);await refresh();}catch{signedIn(false);}})();
setInterval(()=>{if(!busy&&!document.hidden&&!$('dashboard').hidden)void refresh();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!$('dashboard').hidden&&!busy)void refresh();});
`;
