import { portalStyle } from './portal-style.js';
const page = (title: string, body: string, script = '') => `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>${title} — Local Sites</title><style>${portalStyle}main{max-width:960px;margin:auto}h1{font-size:clamp(1.6rem,5vw,2.5rem)}.setup-card{background:#142136;border:1px solid #293b50;border-radius:20px;padding:clamp(16px,4vw,32px);margin:20px 0}.setup-card p{line-height:1.9}.setup-card a{color:#56dfc1}.setup-card a.primary{color:#08251f}.step{font-variant-numeric:tabular-nums;color:#56dfc1}code{overflow-wrap:anywhere}.device-row{padding:20px 0;border-bottom:1px solid #293b50;overflow-wrap:anywhere}.device-row button{margin:8px 8px 0 0;min-height:44px}.device-row input{max-width:100%;min-height:44px}a.link{display:inline-flex;align-items:center;min-height:44px}.setup-card ol{padding-left:24px;line-height:2}</style></head><body><a class="skip-link" href="#main-content">本文へ移動</a><header><div class="brand"><span class="mark" aria-hidden="true">▥</span><strong>Local Sites</strong></div><a class="link" href="/">管理画面へ</a></header><main id="main-content" tabindex="-1">${body}</main>${script?`<script src="${script}" defer></script>`:''}</body></html>`;
export const setupHtml = page('Windows セットアップ', `<p class="eyebrow">WINDOWS 11 · GET STARTED</p><h1>この端末から、Local Sitesへ。</h1><p class="muted">接続先：<code>__SETUP_URL__</code></p><section class="setup-card"><span class="step">01 / 準備</span><h2>証明書と必要なソフトを確認</h2><p>管理者から受け取った公開CA証明書を、現在のユーザーの「信頼されたルート証明機関」に登録してください。ブラウザーの証明書警告が出る場合は先に進まず、管理者に確認してください。</p><p>Windows 11、Codex、Node.js 22以上、tar が必要です。同じLANに接続してください。ソフトの自動インストールは行いません。</p></section><section class="setup-card"><span class="step">02 / ダウンロード</span><h2>セットアップツールを実行</h2><p>ZIPを展開し、START.cmd を開きます。署名されていないスクリプトを実行できない組織管理端末では、管理者に相談してください。</p><a class="link primary" href="/setup/windows.zip" download>Windows用セットアップを取得</a><p>DNSの変更時だけWindowsの管理者承認が必要です。元の設定は保存されます。認証キーはZIPに含まれません。</p></section><section class="setup-card"><span class="step">03 / 承認と接続</span><h2>照合コードを管理者に伝える</h2><p>ツールに表示された端末名と8桁のコードを、設定済み端末の管理者に伝えてください。申請は10分間有効です。承認された端末は、すべてのアプリを管理できます。</p><p>完了後はWindowsからサインアウトして再度サインインし、Codexの新しいタスクで「local-sitesでアプリ一覧を確認して」と依頼してください。</p></section><section class="setup-card"><h2>中断・やり直し</h2><p>失敗した場合は原因を解消して同じツールを再実行してください。受領済みの接続情報は再利用します。DNSだけを元に戻す場合はツールの復元モードを利用できます。詳細はZIP内のREADME-ja.txtをご覧ください。</p></section>`);
export const devicesHtml = page('端末管理', `<p class="eyebrow">DEVICE ACCESS</p><h1>端末の接続を管理</h1><p class="muted">承認した端末は全アプリを管理できます。申請端末の画面に表示されたコードを確認してください。</p><p><a class="link" href="/setup">新しいWindows端末の準備手順</a></p><div id="deviceMessage" role="status" class="notice">読み込み中…</div><button id="reloadDevices">一覧を更新</button><section class="setup-card"><h2>承認待ち・受領待ち</h2><div id="requests"></div></section><section class="setup-card"><h2>登録済み端末</h2><p class="muted">失効は次のリクエストから反映されます。自分の端末を失効すると再ログインできなくなります。</p><div id="devices"></div></section>`, '/devices.js');
export const devicesScript = String.raw`
let csrf='';const $=id=>document.getElementById(id);const node=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
async function api(url,body){const r=await fetch('/api'+url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});if(r.status===401)throw Error('管理画面でログインしてから、このページを開いてください。');const data=await r.json();if(!r.ok)throw Error(data.error||'取得できませんでした。');return data;}
async function action(fn){try{await fn();await refresh();$('deviceMessage').textContent='更新しました。';}catch(e){$('deviceMessage').textContent=e.message;}}
async function refresh(){const data=await api('/devices');for(const [id,items] of [['requests',data.requests],['devices',data.devices]]){const root=$(id);root.replaceChildren();if(!items.length)root.append(node('p','該当する端末はありません。'));for(const item of items){const row=node('article','');row.className='device-row';row.append(node('h3',item.name));const button=(text,fn)=>{const b=node('button',text);b.onclick=()=>action(fn);row.append(b);};if(id==='requests'){row.append(node('p',(item.status==='approved'?'承認済み・受領待ち':'承認待ち')+' · 期限 '+new Date(item.expiresAt).toLocaleTimeString('ja-JP')));if(item.status==='pending'){const label=node('label','端末に表示された8桁のコード '),input=node('input','');input.inputMode='numeric';input.maxLength=8;input.autocomplete='off';label.append(input);row.append(label);button('承認',()=>api('/devices/requests/'+item.id+'/approve',{code:input.value.trim()}));}button('拒否',()=>api('/devices/requests/'+item.id+'/reject',{}));}else{row.append(node('p',item.createdAt?'登録 '+new Date(item.createdAt).toLocaleString('ja-JP'):'既存の端末'));button('接続を失効',async()=>{if(confirm(item.name+' の接続を失効しますか？'))await api('/devices/'+encodeURIComponent(item.name)+'/revoke',{});});}root.append(row);}}}
$('reloadDevices').onclick=()=>action(refresh);(async()=>{try{csrf=(await api('/session')).csrf;await refresh();$('deviceMessage').textContent='最新の一覧です。承認待ちは「一覧を更新」で確認できます。';}catch(e){$('deviceMessage').textContent=e.message;}})();
`;
